### ISSUE TITLE
How can I handle wildcard domain?

### ISSUE THREAD

**Issue by initdc** [fastly/Viceroy#137]
### Problems:

1. I am confused about the `backends` params, it starts with protocol in `fastly.toml` file, and `Host` on web control panel  not (and it should be), how do I setup it correctly? 

2. I built serverless apps runing on Cloudflared Workers before, I am trying port them on fastly `@Edge` as deliver branch. Then I reached problems, with `Workers Routing` I can handle wildcard domain `*.example.com, *-cf.example.com`. The program works   well on Workers. 

3. `@Edge` not serve HTTP request, will get `308 Permanent Redirect`. I can't provide Cert with trial account.

### Refs:

src: https://github.com/initdc/ghuser-fastly
instance: 
  - https://raw-ghuser.mirr.one/initdc/ghuser-fastly/master/fastly.toml
  - https://avatars-ghuser.mirr.one/u/14258692?s=80&v=4

**Comment by cratelyn** [comment]
hi there @initdc!

> 1. I am confused about the `backends` params, it starts with protocol in `fastly.toml` file, and `Host` on web control panel  not (and it should be), how do I setup it correctly?

you might want to check out the Developer Hub reference on the `fastly.toml` format here: https://developer.fastly.com/reference/compute/fastly-toml

as you mentioned, the protocol is included here! iirc, this is to help Viceroy decide how to communicate with the origin server that's been configured.

> 2. I built serverless apps runing on Cloudflared Workers before, I am trying port them on fastly `@Edge` as deliver branch. Then I reached problems, with `Workers Routing` I can handle wildcard domain `*.example.com, *-cf.example.com`. The program works   well on Workers.

i'm not entirely up-to-speed on the details of CF Workers, but if i understand correctly, you're trying to send traffic to origin servers whose URL's are not known in advance? unfortunately, C@E does not support this currently, but i'd recommend reaching out to support@fastly.com for further questions about that!

> 3. `@Edge` not serve HTTP request, will get `308 Permanent Redirect`. I can't provide Cert with trial account.

i'm not sure about this either, but i'd again recommend checking with support@fastly.com. they should be able to provide more guidance about configuring HTTP traffic.

i'm going to close this and let further discussion happen in support channels, since this doesn't appear to be related to any bugs in Viceroy itself. thank you again, for reaching our @initdc, and good luck! :heart_decoration:
