### ISSUE TITLE
Send request - How to not block the request but logging in case of an error?

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#147]
Hi, how can I send a request asynchronously but log information in case of a failure?

```rs
req.send_async(BACKEND);
```

**Comment by cratelyn** [comment]
hi @StarpTech :wave: i'm going to close this issue, as it is a question concerning the Rust SDK, rather than being directly related to Viceroy.

if i may, i'd like to recommend following the advice outlined in [this] comment, and directing these questions to support@fastly.com. the issue tracker here is not intended as a primary support venue, and the support team will be prepared to give you better responses than you'll find here
