### ISSUE TITLE
Rename local Dictionary to local Config Store

### ISSUE THREAD

**Issue by JakeChampion** [fastly/Viceroy#198]
The language SDKs are deprecating their Dictionary implementations in favour of Config Store however when using Viceroy for local development, the way to configure a local Config Store is to create a `local_server.dictionaries` entry in the `fastly.toml` file. -- https://developer.fastly.com/reference/compute/fastly-toml/#dictionaries

It would be nice if that field could also work under the name `local_server.config-stores`, keeping support for `local_server.dictionaries` for all the existing `fastly.toml` manifests out in the world

If this is something we want to do, we'd need to sync with the Fastly CLI project to make sure the CLI also understands the new field

**Comment by Integralist** [comment]
This needs to be closely coordinated with the Fastly CLI because it will update to the latest Viceroy version and that would cause the user's existing configuration in the fastly.toml to be unrecognised.

I would suggest we implement support for both initially and then deprecate the old name.

Alternatively, we would have to cut a release of the CLI that uses a pinned version of Viceroy as its maximum version. But that itself still won't help users who don't update their Fastly CLI version, but still Viceroy gets updated to a latest release. So I would say supporting both with a deprecation notice is the best bet.

**Comment by JakeChampion** [comment]
> This needs to be closely coordinated with the Fastly CLI because it will update to the latest Viceroy version and that would cause the user's existing configuration in the fastly.toml to be unrecognised.

Yep, I've got an issue on the CLI also https://github.com/fastly/cli/issues/700 (I also note that the CLI could maybe become relaxed on the structure of `fastly.toml`)

>I would suggest we implement support for both initially and then deprecate the old name.

Agreed, that's the approach I think we will want to be taking 👍

**Comment by JakeChampion** [comment]
This was added in https://github.com/fastly/Viceroy/pull/240
